version: '3.3'

services:
  postgres:
    container_name: postgres
    image: postgres:12
    ports:
      - 5432:5432
    volumes:
      - /userlogin/postgres/data/:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=docker
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker

  redis:
    container_name: redis
    image: redis:5
    volumes:
      - /userlogin/redis/data/:/data

  node:
    container_name: node
    build:
      context: .
      dockerfile: ./docker/node.dockerfile
    ports:
      - 3333:3333
    environment:
      NODE_ENV: production
    command: bash -c 'yarn migration && yarn start'
    depends_on:
      - redis
      - postgres
    links:
      - redis
      - postgres
