version: '3.3'

services:
  meetapp_postgres:
    container_name: meetapp_postgres
    image: postgres:12
    networks:
      meetapp:
        aliases:
          - postgres
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=docker
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker

  meetapp_redis:
    container_name: meetapp_redis
    networks:
      meetapp:
        aliases:
          - redis
    image: redis:5
    volumes:
      - redis-data:/data

  meetapp_node:
    container_name: meetapp_node
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    networks:
      meetapp:
    ports:
      - 3333:3333
    volumes:
      - .:/home/app
      - /home/app/node_modules
      - /home/app/build
    command: yarn dev
    depends_on:
      - meetapp_postgres
      - meetapp_redis
    links:
      - meetapp_postgres
      - meetapp_redis

volumes:
  postgres-data:
  redis-data:

networks:
  meetapp:
